name: AutoUpdate

on:
  schedule: 
    - cron: '59 23 * * *'
  workflow_dispatch:
    inputs:
      forcerewriteurls:
        description: 'Force Rewrite URLs'
        default: false
        type: boolean
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r parser/requirements.txt
    - name: Run main
      run: python parser/main.py
      env:
        BEAU_FORCEREWRITEURLS: ${{ inputs.forcerewriteurls }}
    - name: Commit changes
      id: commit
      uses: EndBug/add-and-commit@v9
      with:
        add: 'parts/*'
        message: 'Auto Update'
        default_author: github_actions
        push: true
