name: AutoUpdate

on:
  schedule: 
    - cron: '59 23 */3 * *'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r parser/requirements.txt
    - name: Run main
      run: python parser/main.py
    - name: Commit changes
      id: commit
      uses: EndBug/add-and-commit@v9
      with:
        add: 'parts/*'
        message: 'Auto Update'
        default_author: github_actions
        push: true
    - name: ntfy-success
      uses: niniyas/ntfy-action@master
      if: success()
      with:
        url: '${{ secrets.NTFY_URL }}'
        topic: '${{ secrets.NTFY_TOPIC }}'
        tags: heavy_check_mark,croissant,croissant
        title: 'beau-redirect parser.yml'
        details: 'commited: ${{ steps.commit.outputs.commited }}'
    - name: ntfy-fail
      uses: niniyas/ntfy-action@master
      if: failure()
      with:
        url: '${{ secrets.NTFY_URL }}'
        topic: '${{ secrets.NTFY_TOPIC }}'
        tags: negative_squared_cross_mark,croissant,croissant
        title: 'beau-redirect parser.yml failes'
        details: 'FAILED'
