name: AutoUpdate

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r parser/requirements.txt
    - name: Run main
      run: python parser/main.py
    - name: Commit changes
      uses: EndBug/add-and-commit@9
      with:
        add: 'parts/*'
        message: 'Auto Update'
        default_author: github_actions
        push: true
